- draft-barnes-mls-protocol.md
It first reads as if MLS allows groups to communicate with each other, which I don't *think* is the intent.
> "Groups" is ambiguous

- draft-barnes-mls-protocol.md
This PR contains several changes that I just wanted to get in for the IETF 102 deadline.
* Add TreeKEM as an option (leveraging some Beurdouche work)
* Refactor GroupAdd to always do "simulated UserAdd"
* Delete -> Remove
> Updates for IETF 102

- draft-barnes-mls-protocol.md
not sure what was happening here, but moving to the three tilde fixes it.
> fix broken art

- draft-barnes-mls-protocol.md
- draft-ietf-mls-protocol.md
This is one of the options regarding Message Protection discussed in Montreal...
> Message Protection

- draft-ietf-mls-protocol.md
Including the "new" 2119 paragraph.
> updating 2119 paragraph

- draft-ietf-mls-protocol.md
algorithm is now before identity_key for easier parsing
> Change order of fields in UserInitKey struct

- draft-ietf-mls-protocol.md
This PR addresses two outstanding issues with Welcome messages:
1. Welcome messages were not encrypted for the new member, so that the information in them (in particular, init secrets) were not appropriately protected.
2. The protocol overview had not been updated to include the Welcome-based add flow.
> Welcome improvements

- draft-ietf-mls-protocol.md
> fix small typo in GroupState struct

- draft-ietf-mls-protocol.md
> Fix for Application Key Schedule and define HKDF-Expand-Label

- draft-ietf-mls-protocol.md
- Specify padding length
- Rename struct Application to ApplicationMessage
> Message protection improvements

- draft-ietf-mls-protocol.md
Fixes for points 1, 2, 4, 7 in #108.
> Editorial: some fixes for #108

- draft-ietf-mls-protocol.md
Aligning the terminology across the two documents after discussion.
> Update of the terminology

- draft-ietf-mls-protocol.md
This addresses the authentication issue in -03 noted on the mailing list.
> Include a hash of the WelcomeInfo in the Add message

- draft-ietf-mls-protocol.md
> GroupState is not a group state, renaming to GroupContext

- draft-ietf-mls-protocol.md
> Reorder blanking and update in the Remove operation

- draft-ietf-mls-protocol.md
> Rename UserInitKey to ClientInitKey

- draft-ietf-mls-protocol.md
@rozbb pointed out this disconnect in #172, but the fix needs to be the other way around.
> Use correct field names

- draft-ietf-mls-protocol.md
While trying to implement #170 [in mlspp](https://github.com/cisco/mlspp/pull/48), I noticed that the confirmation and transcript hash calculations in draft-06 do not actually allow a new participant to join the transcript hash.  Since the `transcript_hash` value is sent, and not the `intermediate_hash` value, the new joiner is missing the auth data necessary to compute the next `transcript_hash` value.  
To fix this and clarify terminology, this PR makes the following changes:
* `transcript_hash` becomes `confirmed_transcript_hash`, since this is what goes into the confirmation MAC
* `intermediate_hash` becomes `interim_transcript_hash`
* `WelcomeInfo` is updated to refer to the `interim_transcript_hash`
> Fix transcript so that new members get the right information

- draft-ietf-mls-protocol.md
This PR implements a collection of comments on #146.  It aims to achieve the goal stated by @psyoptix of having every derivation have a different relationship, but with a simpler construction.
> Simplify AS tree/ratchet computations

- draft-ietf-mls-protocol.md
Update change log for draft-07
No conflicting PRs so I did break many lines that were too long.
Fix a few minor editorial issues after merging the tree-based application key schedule.
> Minor editorial updates

- draft-ietf-mls-protocol.md
The operations in the lifecycle of a group has been reduced to three.
> Minor edit

- draft-ietf-mls-protocol.md
This PR corrects three minor typos.
> Correction of three minor typos

- draft-ietf-mls-protocol.md
I couldn't find this written anywhere else and this is also related to a discussion about PCS with Cas and al.
> Precisions on authentication and IdentityKeys

- draft-ietf-mls-protocol.md
> External proposals

- draft-ietf-mls-protocol.md
> Add downgrade protection to ClientInitKeys

- draft-ietf-mls-protocol.md
Picking up some comments from @Bren2010 that I missed earlier, and fixing examples.
Obsoletes #232
> Some editorial fixes

- draft-ietf-mls-protocol.md
This is for injection of out-of-band shared entropy.
> Initial proposal for PSK inputs

- draft-ietf-mls-protocol.md
> Add some per-message entropy

- draft-ietf-mls-protocol.md
Since draft-08, we have neglected to update the changelog, despite a bunch of significant changes.  Also, because our CI is busted, some build failures crept in.
> Fix build and update changelog

- draft-ietf-mls-protocol.md
This PR addresses https://github.com/mlswg/mls-architecture/issues/62.
> Rename messaging service to service provider

- draft-ietf-mls-protocol.md
> Use node_index for both hashes

- draft-ietf-mls-protocol.md
> Use correct arguments to Derive-Secret

- draft-ietf-mls-protocol.md
> Use the KDF from HPKE

- draft-ietf-mls-protocol.md
This PR defines and links to the HPKE draft when first introducing this term in the draft.
> Define HPKE on first use

- draft-ietf-mls-protocol.md
cc./ @Bren2010, it should be better now.
> Fix grammar

- draft-ietf-mls-protocol.md
Keep it consistent with #key-schedule
> Fix inconsistency in deriving welcome_secret

- draft-ietf-mls-protocol.md
This PR gets rid of the explicit HMAC reference and uses KDF.Extract instead (which internally uses HMAC). Also `confirmation` is renamed to `confirmation_tag`.
> Confirmation fix

- draft-ietf-mls-protocol.md
Security considerations has gotten a little outdated. Updated with new info
> Update security considerations.

- draft-ietf-mls-protocol.md
This fixes issue #426 . This is originally the work of @chrisbrzuska . I'm only submitting it for administrative purposes.
> Groupcontext as context

- draft-ietf-mls-protocol.md
cc./ @raphaelrobert @beurdouche
> Leave this phrase open to allow deniability

- draft-ietf-mls-protocol.md
> Fix typo Derive-Secret

- draft-ietf-mls-protocol.md
> Pin HPKE to -07.

- draft-ietf-mls-protocol.md
I think this word was left from previous changes to the name of this particular key..
cc./ @raphaelrobert @beurdouche
> Update name for this particular key

- draft-ietf-mls-protocol.md
Fixes #440 (see issue for details).
> Fix the protocol overview section

- draft-ietf-mls-protocol.md
This PR adds text to truncate the tree to perform garbage collection on removal. [ref: https://github.com/mlswg/mls-protocol/pull/84/files]
> Truncate tree size on removal

- draft-ietf-mls-protocol.md
> Inject GroupContext as HPKE info instead of AAD

- draft-ietf-mls-protocol.md
Most of these were stale; see comments for more specifics.  I opened #482 as a general issue arising from the final TODO.
> Remove OPEN ISSUEs and TODOs

- draft-ietf-mls-protocol.md
> Clarify extension handling and make extension updatable

- draft-ietf-mls-protocol.md
> Add group_context_extensions proposal ID

- draft-ietf-mls-protocol.md
> Add ciphersuite field to `PublicGroupStateTBS`

- draft-ietf-mls-protocol.md
This is a follow-up to #501 (which was merged before all comments were addressed).
> Add protocol version to PGS

- draft-ietf-mls-protocol.md
> Recommend against self-Update proposals in Commit

- draft-ietf-mls-protocol.md
> Remove the requirement for Add in external commit

- draft-ietf-mls-protocol.md
> 384 Ciphersuite Addition

- draft-ietf-mls-protocol.md
> Two editorial issues

- draft-ietf-mls-protocol.md
> Revamp overview sections

- draft-ietf-mls-protocol.md
> Require extensions to be unique in any given extensions vector

- draft-ietf-mls-protocol.md
As @kkohbrok noted [on the mailing list](https://mailarchive.ietf.org/arch/msg/mls/P8CiOeQy3lev7s5vbnaRkPwRa1Q/), the current truncation algorithm breaks parent hashes.  This PR implements the "careful truncation" algorithm he proposes.
> Careful truncation

- draft-ietf-mls-protocol.md
> Be consistent about version labeling

- draft-ietf-mls-protocol.md
> Update the description of the evolution of GroupContext

- draft-ietf-mls-protocol.md
Adds the overview text proposed in #525.
> Add branch/init overview

- draft-ietf-mls-protocol.md
Complete the renaming of InitKeys ->  KeyPackages;  and GroupInfo -> PublicGroupState
> Rename InitKeys -> KeyPackages;  and GroupInfo -> PublicGroupState

- draft-ietf-mls-protocol.md
> Exempt default features from RequiredCapabilities

- draft-ietf-mls-protocol.md
> Align cryptographic state description with figure

- draft-ietf-mls-protocol.md
Note that `## Secret Tree` is currently under `# Key Schedule`, so that should probably move or the top level section should be renamed. I ran out of imagination for today.
> Define _key schedule_ and reference in Figure 1

- draft-ietf-mls-protocol.md
> Forbid proposals by reference in external commits

- draft-ietf-mls-protocol.md
Concepts go into the introduction, operations become their own top-level section.
> Split ratchet tree into concepts and operations

- draft-ietf-mls-protocol.md
Depends on #566 
Moves the `Cryptographic Objects` and `Message Framing` sections ahead of `Ratchet Tree Operations`, to reduce forward references and have ratchet tree / key schedule / secret tree sections together.
> Reorg move crypto forward

- draft-ietf-mls-protocol.md
Depends on #567 
Some subsections of `Key Packages` are more natural within the ratchet tree operations section.  This PR pulls them up into the `Ratchet Tree Operations` section.
> Consolidate ratchet-tree-related sections

- draft-ietf-mls-protocol.md
Depends on #568 
This swaps the "Key Packages" and "Key Schedule" sections, so that the former is just before "Group Creation".
> Move Key Packages section down

- draft-ietf-mls-protocol.md
Depends on #569 
As described in the protocol overview, the Secret Tree can be understood apart from the key schedule; the key schedule just provides the `encryption_secret` to become the root of the tree.  This PR pulls out the secret-tree-related subsections of the key schedule section into their own top-level section.
Best reviewed with `git diff reorg-move-kp-down --diff-algorithm=minimal` to show the diff against #569
> Split out Secret Tree

- draft-ietf-mls-protocol.md
Depends on #570 
This PR moves the "Group State" subsection up into the "Key Schedule" section, where it fits more naturally.
> Move up group state

- draft-ietf-mls-protocol.md
While landing #587, I noticed that there were some dangling references left over from the KeyPackage/LeafNode split, e.g., to the "`parent_hash` extension" or `leaf_key_package`.  This PR cleans those up.
> Clean up from KeyPackage/LeafNode split

- draft-ietf-mls-protocol.md
> Normalize on 'copath'

- draft-ietf-mls-protocol.md
> Add version to MLSMessage

- draft-ietf-mls-protocol.md
This PR picks up changes from #609 clarifying and cleaning up a few issues around LeafNode.
> Clean up LeafNode vs. KeyPackage

- draft-ietf-mls-protocol.md
Work in Progress editorial changes.
> Proposed editorial changes

- draft-ietf-mls-protocol.md
This PR adds two clarifications suggested by @rohan-wire:
1. Clarifying some antecedents in UpdatePath processing
2. Explaining how the example trees can come about in practice
> Clarify some things about trees

- README.md
Describe in README.md how to fetch the now required aasvg (ASCII art to SVG) and svgcheck tools.
> Add directions for newly required aasvg tools to README.md

- draft-ietf-mls-protocol.md
Make more ASCII art render as SVG in HTML version of draft.
Fix one instance of pseudocode marked as TLS Presentation Language.
> Continue to make HTML drafts prettier with more SVG

- draft-ietf-mls-protocol.md
> Add missing mention of P-384

- draft-ietf-mls-protocol.md
> Clean up terminology of derived secrets/keys

- draft-ietf-mls-protocol.md
> Clarify secret/key; change to epoch authenticator

- draft-ietf-mls-protocol.md
I drew this to help explain the relevant patch in MLSpp to someone, and thought it might be helpful to other folks.
> Add a diagram showing how the message types relate

- draft-ietf-mls-protocol.md
> Cite AEAD limits draft.

- draft-ietf-mls-protocol.md
> Introduce GroupContext in terminology.

- draft-ietf-mls-protocol.md
Fixes #643 
Changes `MLSMessageCommitContent -> ConfirmedTranscriptHashInput` and `MLSMessageAuthData -> InterimTranscriptHashInput`.
> Better documentation for transcript hash

- draft-ietf-mls-protocol.md
> Use new tree for context in path secret encryption

- draft-ietf-mls-protocol.md
Closes #666 
Also covers the PSK part of #673
> Clean up PSK provisions

- draft-ietf-mls-protocol.md
> Recommend that group ids are generated randomly.

- draft-ietf-mls-protocol.md
Closes #672 
Summary:
``` diff
-## Adding and Removing Leaves
+## Update Paths
+## Adding and Removing Leaves
-## Update Paths
-#### Joining via External Commits
-## Ratchet Tree Extension
+#### Joining via External Commits
+#### Ratchet Tree Extension
```
> Minor section reorder

- draft-ietf-mls-protocol.md
Constructed from the highlights of PR titles, with breaking changes indicated with `(*)` as usual.
> Add changelog for draft-15

- draft-ietf-mls-protocol.md
To check whether there actually is a problem, I made the fix for #719, and it seems to work as designed.
> Fix #719 (contributors section)

- draft-ietf-mls-protocol.md
> Add signature input to VerifyWithLabel

- draft-ietf-mls-protocol.md
> Update Jon's details

- draft-ietf-mls-protocol.md
Mostly this is semicolons at the end of every statement.
> presentation syntax tweaks

- draft-ietf-mls-protocol.md
This PR changes the affiliation of @raphaelrobert and myself.
> Change of affiliation

- draft-ietf-mls-protocol.md
Thanks to Gorry Fairhurst:
https://mailarchive.ietf.org/arch/msg/mls/ju2j3jsdttOfC06OedFFvZN73l8/
> Address TSV-ART review comments

- draft-ietf-mls-protocol.md
https://mailarchive.ietf.org/arch/msg/mls/g9XmmtT5wtxjazHrUVdW27a---U/
> Responses to early ARTART review

- draft-ietf-mls-protocol.md
#755 made me realize that BasicCredential actually doesn't exist anymore!
> Remove reference to BasicCredential.

- draft-ietf-mls-protocol.md
Fixes #780 
Fixes #781
Fixes #797
Fixes #798
Fixes #799
Fixes #801
Fixes #814
Fixes #817
> Minor edits for AD comments

- draft-ietf-mls-protocol.md
> Address nits

- draft-ietf-mls-protocol.md
> Make ProtocolVersion two bytes

- draft-ietf-mls-protocol.md
Fixes #825 
cc @kkohbrok  for review
> Clarify that the AS needs to vet the signature key

- draft-ietf-mls-protocol.md
https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/ballot/#draft-ietf-mls-protocol_roman-danyliw
> IESG Review from Roman Danyliw

- draft-ietf-mls-protocol.md
https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/ballot/#draft-ietf-mls-protocol_zaheduzzaman-sarker
> IESG Review by Zaheduzzaman Sarker

- draft-ietf-mls-protocol.md
https://datatracker.ietf.org/iesg/agenda/#draft-ietf-mls-protocol_eric-vyncke
> IESG Review from Éric Vyncke

- draft-ietf-mls-protocol.md
- Replace stray instance of MLSCiphertext with PrivateMessage
> Fix inconsistencies and NITS in -17

- draft-ietf-mls-protocol.md
This PR adds a few more key points to the security considerations that probably deserve to be in this document.
> Security considerations

- draft-ietf-mls-protocol.md
Fixes #846 
Also adds a draft-18 section to cover any edits between now and the next I-D.
> Add changelong for draft-16 through draft-18
