mlswg/mls-protocol

- .gitignore
- LICENSE.md
- README.md
- draft-ietf-mls-protocol.md
Note: If you have an existing clone, you will need to delete `.targets.mk` at the root level of the clone in order for `make submit` to work. (`make` will still work fine)
> Rename from draft-barnes to draft-ietf

- draft-ietf-mls-protocol.md
I would like to remove the UserAdd functionality that's in the current document, and the GroupInitKey construct that supports it.  We will need to support a flow where a device can join without an explicit invite.  But that mechanism will also have to be limited,  since it leaks information out of the group.  It will be cleaner to get a GroupAdd-only system working first, then figure out how to add this back in.
> Remove UserAdd

- draft-ietf-mls-protocol.md
There was agreement at the MLS interim of September 2018 to focus further development on TreeKEM, not ART.  This PR implements that change.
> Remove ART

- draft-ietf-mls-protocol.md
There are two "Terminology" sections so I renamed the 2nd one "Tree Computations Terminology" to match the reference in s2.
> renaming s5.1

- draft-ietf-mls-protocol.md
There is no reason for the members of a conversation to keep the whole history of group operations, but they should agree on it.
> Convert transcript to a hash

- draft-ietf-mls-protocol.md
This PR updates the procedures for Add and Remove to remove double-joins.  The cost is a potential increase in the size of GroupOperation messages in the case of incomplete trees.
Depends on #66
> Remove double-join with the "partial tree" approach

- draft-ietf-mls-protocol.md
At the MLS interim, the major feedback regarding authentication was that it would be good practice to provide explicit key confirmation.  This PR adds an explicit confirmation field to Handshake messages, containing a MAC over the proposed (updated) state of the group, together with the latest handshake message.
> Add explicit key confirmation

- draft-ietf-mls-protocol.md
Need some actual values here for interop.  Signature scheme values are a subset of those in RFC 8446.
@raphaelrobert - Do you think we should go ahead and define the higher-security-level ciphersuites as well as signature algorithms?
> Add ciphersuites and signature schemes

- draft-ietf-mls-protocol.md
The very first commit from PR #106 (6ba86ff561484a9eb96012e3b55b49f23cb8f9e9) was removed and a separate Issue #110 is filled for unifying the use of "`" and "_".
> Merging some commits from PR #106

- draft-ietf-mls-protocol.md
I forgot to update the changelog before I published -03.  We should add that to the review criteria.  This will at least fix it for -04.
> Update changelong with entries for -03

- draft-ietf-mls-protocol.md
For now, I've only touched the sections until the "Cryptographic Objects" section, which seems to be outdated anyway. Once those are updated at some point, I'm happy to help moving from hashing to KDF-derivation there as well.
> Use a KDF instead of a hash function to get keys for parent nodes

- draft-ietf-mls-protocol.md
This does not handle the removal of DH uses instead of KEM which will be done as part of Issue #95 / PR #113 ...
> Rename ECIES to HPKE

- draft-ietf-mls-protocol.md
There is no "leaf_secret" field in GroupState. While there might be one in the group state struct that the implementation maintains locally, I think it's safe to recommend copying everything from the GroupState object as it's defined earlier in the document.
> Rephrased sentence in Add section.

- draft-ietf-mls-protocol.md
Right now, we blank out leaf nodes when we remove their holders, but we never reduce the size of hte tree or repopulate interior blanks with new members.  This PR adds those functions:
* Reduce the size of the tree and the roster when you remove from the right edge
* Add an `index` field to the `Add` message, to enable new members to be added to blank slots in the tree, not just at the right edge.
In addition to performing "garbage collection", this change should make it easier to do a state resync -- just remove the desync'ed endpoint and add them back in the same spot.
Fixes #86
> Garbage collection

- draft-ietf-mls-protocol.md
This just adds some fields for devices to declare their version support in UserInitKey and for group members to declare what version the group is using in WelcomeInfo.  Obviously, more subtlety will be needed, but this seems like an OK shim for -04.
Cf. #105
> Add version negotiation fields

- draft-ietf-mls-protocol.md
Initial attempt to solve #129. This defines the KDF as discussed in #129 and relocates the DH computation obligation and verification as part of the Derive-Key-Pair function definition.
> Initial definition of the KDF and the Derive-Key-Pair function

- draft-ietf-mls-protocol.md
Adding this check would be the first step in recognizing that an Update operation may have maliciously excluded a person from the group.
> Added that users SHOULD verify pubkeys in an Update

- draft-ietf-mls-protocol.md
This clears up the wording around how to prune the ratchet tree on a Remove operation. Previously, it could be interpreted as "remove nodes from the tree until the rightmost node is not null", but this is not what is intended by the authors, and it also has the ability to produce invalid trees (i.e., trees with an even number of elements).
The second change is to do the truncation _after_ doing the Blank propogation up the direct path of the removed leaf. Note that the order of these steps doesn't matter in that they produce the same resulting tree. However, if we blank after pruning, an implementor would have to take care to not to try to blank out previously-removed nodes. Prune-then-blank is a little easier to reason about.
The third change is a semantic fix. It is clear from the last …
> Fixes to tree manipulation in Remove

- draft-ietf-mls-protocol.md
> Fix typo after change in the MLSCiphertextContent struct

- draft-ietf-mls-protocol.md
"The update secret resulting from this change is the path secret for the
root node of the ratchet tree." is suspicious because in the derivation, the index for both the `path_secret` and `node_secret` is the same as the level of the node. It should be the `path_secret[n+1]` "above the root" and not "for the root" (`path_secret[n]`which is the one used to derive the `node_secret[n]` of the root)...
> Fix incorrect definition of update_secret

- draft-ietf-mls-protocol.md
This PR addresses two issues that were noted in draft-05, one that is definitely a bug, and one that should improve security analysis.
* In draft-05, a circular dependency was introduced, wherein the confirmation MAC was calculated from the transcript, which includes the GroupOperation, which includes the confirmation MAC.  Here we move the confirmation MAC up to the MLSPlaintext object to avoid this circularity.
* In all prior versions, the transcript covered only the GroupOperation objects, not the sender metadata or signatures.  Here we cover the whole MLSPlaintext object, but in "staggered" form -- the confirmation MAC and signature aren't entered into the transcript until the next epoch.
Fixes #157
> Confirmation and transcript improvements

- draft-ietf-mls-protocol.md
The underscore character does not have to be escaped in code environments. This applies to the inline (backticks) as well as block (tildes) variants.
> Formatting: removed `\_` where it was syntactically incorrect

- draft-ietf-mls-protocol.md
@beurdouche has been doing a lot of work, and I just noticed he's not on the list of co-authors.  In addition to recognizing his contribution, this will enable him to push new Internet-Draft versions.
> Add Beurdouche as a co-author

- draft-ietf-mls-protocol.md
Basic idea: 
- Application Key Schedule consists of a left balanced binary tree of secrets (the "AS Tree") and one symmetric ratchet per group member. The AS Tree has the same node/edge structure as the ratchet tree for that epoch. Members are assigned the same leaves.
- Each node in the AS Tree is assigned a secret. The root's secret = application_secret. The secrets of children are derived from that of their parent.
- The secret of a leaf is the initial secret of a symmetric hash ratchet. The ratchet generates the key/nonce sequence used by the leaf's group member to encrypt messages during that epoch.
Other comments:
- I included a "Deletion Schedule": keys, nonces are 'consumed' if they are used to encrypt or successfully decrypt a message. secrets are 'consumed' if value derived from …
> Tree based app keyschedule

- draft-ietf-mls-protocol.md
This is something we've been meaning to do for a while, and just haven't gotten around to.
The Init message directly creates a group with a specified member list.  The cost of group creation is O(N) DH operations for the sender, and O(1) for receivers.
> Specify an Init message

- draft-ietf-mls-protocol.md
Prior drafts enabled encryption of handshake messages, via the common framing structure.  This had the unfortunate effect of making it impossible to add new members!  If an Add is sent encrypted, then the new joiner had no way to get the key to decrypt it.
This PR adds the key and nonce for the Add encryption to the corresponding WelcomeInfo structure.  This maintains the confidentiality of the Add because the WelcomeInfo is encrypted to the new joiner, while providing the new joiner the key material it needs to decrypt the Add.
> Enable new joiners to decrypt an encrypted Add message

- draft-ietf-mls-protocol.md
Currently you assume that the KEM's output is an ephemeral public key, but that's only true for Diffie-Hellman-type constructions.
> HPKECiphertext takes generic KEM output, not a public key.

- draft-ietf-mls-protocol.md
One of the issues was that the ciphersuites were subsubsections in a section, so it got rendered as
```
6.1) Curve25519, SHA-256, and AES-128-GCM
6.1.1) P-256, SHA-256, and AES-128-GCM
```
which is odd.
Also, previously, the beginning of the Cryptographic Objects section talked about ciphersuites and public keys. I moved their descriptions to where they are more relevant.
Finally, I replaced "cipher suite" with "ciphersuite", since the latter had 25 occurrences while the former had 2.
> Cleaned up beginning of Cryptographic Objects section

- draft-ietf-mls-protocol.md
I don't like the pattern of having a marker byte followed by zero-padding. It has to be parsed manually, backwards, unlike every other object in the protocol which all follow a common format.
> Change ciphertext content to be standard TLS format.

- draft-ietf-mls-protocol.md
[As previously discussed](https://mailarchive.ietf.org/arch/msg/mls/jB5ygAJs3P8TLkduj6Q9vFWmSJI), this is a proposal to add AAD to the application messages.
There are many motivations to do this:
• It's a 'cheap' feature to add (although it could potentially be misused)
• It avoids duplicate content: if there is a content that needs to be authenticated, but also needs to be visible to the server, the only solution today is to repeat it in the header (to the server) and then in the encrypted body.
• Modern ciphers already provide support for AAD, and MLS takes advantage of this. In fact most(all?) of the fields in the header are authenticated already.
• This field is optional(as in: can be empty), which means that it doesn't have to be used in the implementation.
The primary benefit is for …
> Add authenticated_data to the mls message.

- draft-ietf-mls-protocol.md
This PR implements the proposal discussed in Prague and on the mailing list, to separate GroupOperations into Proposals and Commits.  This change leaves the underlying ratchet tree operations untouched, but changes how these operations are folded into the overall key schedule.
This is also a fairly initial effort, with several OPEN ISSUEs noted.  The most important IMO is that we should allow a single MLSPlaintext to pack one or more Proposals along with a Commit, which makes it simpler to emulate the current behavior, and might allow us to get rid of the Init message.
> Proposals and Commits

- draft-ietf-mls-protocol.md
This PR begins filling in the IANA Considerations section, starting with a Ciphersuites registry.  This addresses the concerns in #95 as discussed at the interim (2019-10), namely by reserving for vendor use chunk of the code points space large enough to be selected at random without huge risk of collision (2^12 values).
Depends on #209 
Fixes #95
> IANA Considerations

- draft-ietf-mls-protocol.md
This makes MLSPlaintext signatures and DirectPath encryptions specific to a given group and epoch, to avoid copy/paste attacks.
@Bren2010 - Note that this fixes #214 since DirectPath HPKE encryptions will have non-empty AAD, while Welcome messages will have none.
Depends on #209 
Fixes #214 
Fixes #217
> Add GroupContext to signatures and AAD

- draft-ietf-mls-protocol.md
This PR attempts to implement the "non-destructive add" proposal discussed at IETF 105.  Instead of blanking nodes on add, we keep track of "unmerged leaves" below each intermediate node.  This involves a bit more complexity in the tree state that is passed around, but avoids unnecessary blank nodes.
> Non-destructive add

- draft-ietf-mls-protocol.md
This has been reported unclear multiple times. I strongly prefer forbidding reuse altogether.
A validation mechanism is needed for the formal security proof, it can be implemented according to an expiration mechanism (see Architecture - 4.2.  Delivery Service Compromise)
> Favor not reusing ClientInitKey reuse (SHOULD)

- draft-ietf-mls-protocol.md
This PR makes two major changes that are enabled by Proposals:
* Multiple participants added in the same epoch receive the same Welcome message
* Init is always a special case of Add
Prior to Proposals, treating Init as a special case of Add led to a performance degradation (`n -> n log n`).  With Proposals, any number of Adds can be done with a single Commit (at `O(n)` cost), so there is no more degradation.  The result seems (IMO) much more elegant than before.
The main cost is that encryption of Welcome messages is now in two stages (three if you include the internal HPKE stage!), even if there is only one new member.
Depends on #209 
Obsoletes #192 and #194
> Welcome* == Init

- draft-ietf-mls-protocol.md
This is a light optimization over #209, removing the overhead of extra encryptions/signatures in the case where proposal(s) and a commit are sent at the same time.
Depends on #209
> Pack multiple Proposals and a Commit together

- draft-ietf-mls-protocol.md
- Blanking on add (I think) was obsoleted by unmerged leaves
- Add leaf to unmerged list for *non-blank* nodes on add
- There are now four elements in each node
> Remove blanking of nodes on Add, clarify language

- draft-ietf-mls-protocol.md
I have managed to implement Proposal / Commit in mlspp, but it required some modifications to the Welcome and Commit structs and processes.  Two major things to point out:
* This PR proposes to send the same DirectPath to both new members and current members.  This avoids the need to have two code paths and special tree math to implant path secrets, at the cost of some bloat in the Welcome and Commit messages.
* As a result, the sequencing of GroupContexts is a bit tricky.  The GroupContext used for encrypting/decrypting DirectPaths is an intermediate context -- the new group context, but *before the transcript is updated*.  
All that said, this version is [verified implementable](https://github.com/cisco/mlspp/pull/64).  The implementation exercise highlighted that the net effect of …
> Align spec text with implementation

- draft-ietf-mls-protocol.md
Action item from Singapore: it seems better to specify directly in the message if we have an external sender instead of using reserved ranges.
> Change special values to structed types for external senders

- draft-ietf-mls-protocol.md
1. The `client_init_key_id` is no longer needed, since CIKs are referenced by hash.
2. ProposalIDs were no longer usable to refer to proposals since we enabled multiple proposals per MLSPlaintext
3. The syntax description for Welcome was invalid
> Bugfixes in ClientInitKey, Commit, and Welcome

- draft-ietf-mls-protocol.md
1. Once a new member instantiates the group state, they can verify the confirmation MAC that was sent in the Commit that created the state.  This lets new members verify that they've joined correctly.  (It does not assure that they're seeing the same confirmation as anyone else.)
2. Instead of generating a fresh key, we can simply provide the epoch key in the key package and derive the GroupInfo encryption key from it.  This avoids relying on fresh entropy, and makes it more difficult for the sender to provide different keys that will all decrypt and authenticate the GroupInfo.
> Welcome confirmation and key derivation

- draft-ietf-mls-protocol.md
Ignored proposals don't make sense to me. How can they possibly add value? Also, re-structured section on Commits some.
> Get rid of ignored proposals.

- draft-ietf-mls-protocol.md
This PR adapts the Welcome logic so that the new joiners get their path secrets directly, rather than from a DirectPath.  This cleans things up in a few ways.  The new joiners no longer have to have the context for the previous epoch (which was used to encrypt the DirectPath).  And we can get away with one HPKE operation per new joiner instead of two (one for the EncryptedKeyPackage and one for the DirectPath).
The major cost is that there's a bit more complexity in the TreeKEM.  Instead of just producing and consuming DirectPaths, you now need to know which path secrets go with which nodes.  You also need tree math to identify the common ancestor of two leaves, but there's a simple closed-form formula for that, expressed in the Python code here.
[Corresponding PR on the Go …
> Use path secret instead of full DirectPath

- draft-ietf-mls-protocol.md
This PR changes the variable name `HkdfLabel` to `HKDFLabel` in order to match the previously used naming conventions.
> Update HKDFLabel variable to match naming conventions

- draft-ietf-mls-protocol.md
The current draft uses a hash ratchet to derive single-use keys for application messages, but for handshake messages, re-uses the same key with a sequence of different nonces.  This results in a lot of unnecessary extra code.
This PR uses the same hash ratchet for handshake and application messages.  The only difference is in the base key for the hash ratchet.  In the application case, we use the AStree.  In the HS case, we derive the base keys directly from the handshake secret.  The lack of a tree in the HS case means that either the client will do a linear number of derivations on the first send/receive, or it will keep the handshake secret around and not get FS for handshake messages within the epoch.
> Use the same ratchet for Handshake and Application keys

- draft-ietf-mls-protocol.md
Extensions in the CIK were only half of the story.  To do things like RTreeKEM or fork/merge as extensions, we need the ability to (1) tell new members that the group is doing something different, and (2) confirm that all group members have the same view of the rules of the road.  This PR adds extensions to the GroupInfo object for the first case, and to the Welcome object for the second, and a bunch of explanatory text to make it all work.
One thing this PR does *not* do is define a way to change extensions in a running group.  You could in principle do this by sending new extensions in Commit that could overwrite or add to extensions.  But that entails some messy questions (how do you delete an extension in use?), so it is currently left to an extension (heh), or to a group restart. …
> Flesh out the extensions story

- draft-ietf-mls-protocol.md
#279 required a common signature algorithm, but allowed credentials to deviate.  This PR adds the requirement that credentials be consistent.
> Clarify signature algorithm requirements

- draft-ietf-mls-protocol.md
This is just a terminology change.  ClientInitKey was feeling increasingly awkward, because (1) ClientInitKey structs are now used in leaves in addition to being used for initialization, and (2) there are some emerging cases where the "client" in an MLS sense might be a "server" (or some other role) in another application.  "KeyPackage" is a more neutral term.
Other than `s/ClientInitKey/KeyPackage/g`, the most invasive change was in Welcome, where we already had `KeyPackage` and `EncryptedKeyPackage`.  I just changed those to `GroupSecrets` and `EncryptedGroupSecrets`, which seem more descriptive anyway.
Depends on #314
> ClientInitKey -> KeyPackage

- draft-ietf-mls-protocol.md
Closes #300 by updating the description for creating a commit to explicitly mention that first all update proposals are applied, then remove proposals, and last add proposals.
> Explicitly state the order in which proposals are applied when creating a commit

- draft-ietf-mls-protocol.md
In the latest HPKE draft (draft-irtf-cfrg-hpke-04), "Initiator (I)" was renamed to "Sender (S)".
> Fix HPKE setup function name

- draft-ietf-mls-protocol.md
The co-path might contain a high number of resolved nodes when the tree is still empty. The worst case is ~N which is why the limit should be the same as for sender ID.
> Upper bound on group size in early phase too low

- draft-ietf-mls-protocol.md
When we converted to the Proposal/Commit scheme, one of the consequences was that Adds became O(N) instead of O(1), since they had to Committed and commits encrypt the committer's direct path to the remainder of the tree.  This is ~log(N) in the nice case and ~N in the worst case.  At the time, we noted that one could special-case Add-only Commits in the future and make the update to the direct path optional in that case.
This PR implements that suggestion.  The leaf KeyPackage for the Commit is moved into the DirectPath struct, and the whole DirectPath is made optional.  The optional value MUST be provided for:
* A Commit committing an update or remove
* A "just update my path" Commit covering no proposals
> Make ratcheting optional for Adds

- draft-ietf-mls-protocol.md
The first commit is editorial. I removed all the DH terminology I could find and replaced it with KEM terminology.
The second commit is related to https://github.com/cfrg/draft-irtf-cfrg-hpke/pull/79. It would massively reduce complexity of implementations if people were able to rely on HPKE to do all private key parsing, key validation, public key computation, etc. Currently, all the information in the deleted CFRG and NIST sections is either redundant (performed by HPKE) or outdated and performed correctly by HPKE (e.g., old P-256 DH secret representation). Instead of having all this duplicated, it would be easier to keep it in one place.
An issue with the new definition of `Derive-Key-Pair`: Repeatedly calling `HKDF-Expand-Label` can be computationally expensive. Each call requires …
> Rely More on HPKE

- draft-ietf-mls-protocol.md
The upper bound for the number of Proposals of each type in a Commit is currently 2^16.
This makes it impossible to create groups with more than 2^16 members in one go and it also limits the number of UpdateProposals and RemoveProposals that can happen between two Commits to 2^16.
> Upper bound for Commit

- draft-ietf-mls-protocol.md
Fixes #323 by special-casing external senders. Removing the GroupContext would allow me to take messages that user A sent in one instance of a group, and make it look like they're speaking in another group by re-encrypting the ciphertext.
> Allow external proposals to be signed.

- draft-ietf-mls-protocol.md
I've put a bunch of little fixes in here.  If you disagree with any of these changes, I can back them out or change them.
- maximal is defined but never used
- k-th leaf/leaf index is defined in two places; merge definitions
- change KeyPackage struct definition to reflect that ~2~ 3 extensions are required
- `lifetime` is also a required extension
- grammar fix
- add missing semicolon
> misc little fixes

- draft-ietf-mls-protocol.md
With any AEAD, the nonce is necessarily already authenticated. Also, the name of the struct was changed to be more clear.
> Remove nonce from SenderData AAD.

- .editorconfig
- draft-ietf-mls-protocol.md
Previously we used [[ ... ]] for comments, and the body of the comment was only getting elided because the compiler didn't know what that syntax meant.
> Fix all compiler warnings.

- draft-ietf-mls-protocol.md
This PR makes a few minor fixes to extensions:
* Coalesces `supported_versions` and `supported_ciphersuites` into a single extension
* Adds a list of supported extensions in parallel with the versions and ciphersuites
* Adds a missing value to the IANA table for the `ratchet_tree` extension
> Minor extension fixes

- draft-ietf-mls-protocol.md
This PR tries to clarify these paragraphs by the following: 
- Differentiating between HPKE public/private keys when describing how these keys are rotated for a commit
- Clarifying who does the actions associated with a commit
- Adding consistency fixes between the two paragraphs
Let me know if these fixes are not quite right, as this PR tries to clarify where I had questions when reading.
> Commit Generation Clarifications

- draft-ietf-mls-protocol.md
This PR rearranges the key schedule so that the following values are all fed into the init secret to form epoch secret:
1. The commit secret
2. The PSK (if any)
3. The group context
This assures that new joiners know the PSK for the epoch, since they now need to know it to compute the epoch secret.  It also moves the group context from the `Derive-Secret` calls under the epoch secret to the derivation of the epoch secret itself, ensuring that everything derived in the epoch has the same context folded in.
Fixes #325 
Fixes #326
> Reorder key schedule inputs

- draft-ietf-mls-protocol.md
This PR does the following: 
- Adds a lead-in sentence describing how this section builds on the prior. 
- Differentiates between public keys for nodes and public keys for leaves (users)
- Clarifies when secret key material needs to be deleted. 
I also wanted to make a couple other changes, but wanted feedback first. 
1. This section describes the private value corresponding to a node's public key as 'ns[0]' (or node secret), whereas the prior section referred to it as 'np[0]' (or node_priv). It would be better to have these terms be consistent.
2.  On line 773, it says that the client "...transmits a handshake message containing a set of **public** values" and on line 776 it says that "other members of the group can use these **public** values to update". However, this values seems to be …
> Readability edits for section 'Synchronizing Views of the Tree'

- draft-ietf-mls-protocol.md
This PR adds a fix mentioned in #378 but was not included in the PR that was eventually merged. Specifically, both **public and encrypted private** values are sent in a message containing key material to ratchet the tree forward.
> Consistency fix for description of key material sent in an update message

- draft-ietf-mls-protocol.md
This suggestion is based on a discussion in the MLS mailing list [[1]](https://mailarchive.ietf.org/arch/msg/mls/qrpAoK7aNSzKxX4O60pOLvM3cp8). It prevents issues that currently arrise when the very first commit of a group is an "add-only" commit because both the `commit_secret` and `init_secret` would be **0**.
Let me know if the wording or anything else should be changed.
/cc @bifurcation
---
1. https://mailarchive.ietf.org/arch/msg/mls/qrpAoK7aNSzKxX4O60pOLvM3cp8
> Require the initial init_secret to be a random value

- draft-ietf-mls-protocol.md
A couple of minor editorial changes to the current draft, namely:
<details>
<summary>There was a missing grave accent in one of the paragraphs of <a href="https://github.com/mlswg/mls-protocol/blob/c3db39266505e9d202158d642d65918d35870e77/draft-ietf-mls-protocol.md#commit">the Commit section</a> causing some formatting issues</summary>
**Before**:
**After**:
</details>
<details>
<summary>Fix typo Pre-Shared Keys section</summary>
[...], it does not necessarily provide the same [...] guarantees ~than~ as a Commit message.
</details>
<details>
<summary>Resolve remaining reference to <code>prior_epoch</code></summary>
In the Sequencing section there was a reference to a `prior_epoch` field that was introduced in 2fa6ed3c6afc7d308905255b4cabe154a48d1e4b. However, in …
> 4 editorial edits to the draft

- draft-ietf-mls-protocol.md
Addresses ambiguity pointed out on the mailing list by @ericcornelissen.
Fixes #386
> Clarify the transcript hash computation

- draft-ietf-mls-protocol.md
- 0 is invalid for all enums except a few, and I wasn't sure if it mattered? So I made them consistent
- `DirectPath.nodes` needs to be 2^32 to fit the largest DirectPathNode
- Make the `extensions` array 2^32 as well to fit the largest Extension, and also 2^16 for *all* extensions seems small
> Make composite types 2^32 and make 0 invalid for enums

- draft-ietf-mls-protocol.md
Closes #390
As discussed on [the mailing list](https://mailarchive.ietf.org/arch/msg/mls/CbBEhH5A7OyoP6Mf5FFXgSU0r30/) this removes the paragraph in the Group Creation section specifying that joiners SHOULD verify group creation if it is detected. A recent change to group creation - namely a random initial `init_secret` - makes it impossible to verify group creation.
> Remove requirement to verify the group creation process

- draft-ietf-mls-protocol.md
This is a simple rename of `DirectPath` to `UpdatePath` to be more descriptive of the action being performed by the message.
I'll open a separate PR after this PIR is merged with updates to the spec where it uses `Commit` when instead it should say `UpdatePath` (since not every `Commit` actually ratchets forward key material, as I understand). Some examples of where these clarifications should happen are: 
- Line 1203 should instead say "each MLS UpdatePath message" 
- The sections "Ratchet Tree Evolution" and "Sychronizing Views of the Tree" should describe the process of generating the key material for an `UpdatePath` message
cc @bifurcation
> Rename DirectPath to UpdatePath

- draft-ietf-mls-protocol.md
@ericcornelissen pointed out on the mailing list that path secrets are currently used with both KDF.Expand and KEM.DeriveKeyPair.  This PR introduces an extra KDF.Expand call so that each key is used with exactly one algorithm.
> Always use path secrets with KDF.Expand

- draft-ietf-mls-protocol.md
This PR updates two sections to reference generating and sending an `UpdatePath` message, as not all Commits transmit fresh key material (as discussed in #391). 
This PR also includes light editorial edits for clarity and adds detail around the steps to perform an update.
Section 7.7 `Update Paths` currently says that "each MLS Commit message needs to transmit a KeyPackage leaf and node values along its direct path", but section 10.2 `Commit` says that an UpdatePath is optional. I can update 7.7 as well, if 10.2 is correct.
> Use UpdatePath instead of Commit when describing tree updates

- draft-ietf-mls-protocol.md
Fixes #392 
(Also, when I made the change from `KEM.Nsk` to `KDF.Nh`, I realized that the calls to `ExpandWithLabel` all had the same structure as `DeriveSecret`, so I changed to just call DeriveSecret directly.)
> Use full-size path secrets

- draft-ietf-mls-protocol.md
The public key in a credential is introduced without a special name and the field in the BasicCredential is currently called public_key, which is not very expressive. A few paragraphs below, it is referenced as "Identity Key" or simply "Identity", which is a bit misleading, as Credentials are supposed to contain an additional "identity" which is not the key.
I propose we clear up the terminology a bit here and refer to the public key contained in a Credential as "Signature Key".
> Rename identity key to signature key

- draft-ietf-mls-protocol.md
Rotating keys is important and in some cases, Signature Keys are not going to be very "long-term". Instead they're going to be rotated periodically.
I thus propose we simply remove the assumption that Signature Keys are of a "long-term" nature (or otherwise "long-lived"). 
The second change in this PR is that I added a few words indicating explicitly that the identity must not change when updating a KeyPackage.
> Remove long term and explicitly prevent changing of identity

- draft-ietf-mls-protocol.md
This PR adds clarification around X509 cert structure, the chain and its encoding X509.
> Clarify X509Credential structure

- draft-ietf-mls-protocol.md
[Joël pointed out on the list](https://mailarchive.ietf.org/arch/msg/mls/LFz5nC4BnNTf7-OGIac5_QdlCRs/) that MLSPlaintext does not currently authenticate the sender's membership on the group, and as a result, some important attacks arise.  Discussion on the list indicated that adding a MAC with a key derived from the key schedule would provide this authentication.  This PR implements that suggestion.
> Authenticate group membership in MLSPlaintext

- draft-ietf-mls-protocol.md
The credentials we have defined at the moment only contain a single public key and no information regarding what signature scheme that keypair works with (even though the Spec actually says it should include the signature scheme as well).
It would be nice, however, to support potential CredentialTypes that, similar to KeyPackages, include multiple supported signature schemes, each accompanied by a corresponding public key.
The Key that should be used in any given group is then determined by the CipherSuite of the group (which includes a Signature Scheme). When choosing a KeyPackage of a new member, it has to be one that contains a Credential which supports that Signature Scheme.
Note, that I'm not suggesting that this be the case in all Credentials, or even that we change the …
> Allow for credentials supporting multiple signature schemes

- draft-ietf-mls-protocol.md
As discussed in the mailing list, not having the signature contribute to the new epoch's key schedule leads to a one-off effect where parties stay in sync (with respect to keys) for one more epoch, before inevitably go out of sync. This pull request addresses this issue by including the signature in the confirmed transcript hash rather than the interim transcript hash. See the mailing list for a security consideration of this change.
Credit: This pull request was primarily authored by Marta Mularczk; I'm just posting it here for administrative reasons.
> Inlclude the signature in the confirmation tag

- draft-ietf-mls-protocol.md
The authentication_secret was previously in a PR and agreed, but seems to have been removed from the key schedule (possibly during a merge). The discussion on its use is still present. This PR is just to add it back in to the key schedule.
> Authentication Secret

- draft-ietf-mls-protocol.md
Thanks @Bren2010 pointing out the imprecision. Is this what you were looking for?
Thanks @bifurcation for the pointer to the correct registry.
> make IANA reference for Signature Schemes more precise

- draft-ietf-mls-protocol.md
As briefly explained in the mailing list, commit messages currently contain encryptions for newly added group members that never even receive this commit message. This PR explicitely exlcudes them during the preparation of the UpdatePath.
> No redundant ciphertexts

- draft-ietf-mls-protocol.md
This avoids extra signatures and message overhead in the case where the committer is originating proposals.
> Allow proposals by value in Commit

- draft-ietf-mls-protocol.md
As discussed on 2020-10-20, this field is not needed now that #416 moved the signature under the confirmation tag.
> Remove interim transcript hash from GroupInfo

- draft-ietf-mls-protocol.md
Some clarifications and typos from my attempt to understand secret trees and the deletion schedule. Please verify that I'm correct in that `joiner_secret` and `member_secret` also need to be consumed.
> Secret Tree: clarifications and typos

- draft-ietf-mls-protocol.md
We have a changelog for the document by I-D release, but haven't been updating it as we go.  This PR updates the changelog based on merged PRs and the few we expect to close before releasing draft-10.
Marking this as draft right now, until the other PRs have merged.
> Update changelog for draft-10

- draft-ietf-mls-protocol.md
I think that this change will reduce the chance for [confusion](https://mailarchive.ietf.org/arch/msg/mls/UIWuwPC3ukryFUOANyH4cX4et3o/), as now the Parent Hash section will be self-contained, rather than needing to also look into the Tree Hashes section.  Also, it should hopefully be clearer that the `parent_hash` field in the `ParentNode` struct is calculated as the hash of another `ParentNode` struct, rather than the hash of a `ParentNodeHashInput`.
(Though I don't see anywhere that says what to use as `parent_hash` when the `ParentNode` refers to the root.)
> move definition of ParentNode earlier

- draft-ietf-mls-protocol.md
It looks like `key_package`  in Commit was moved to `leaf_key_package` in UpdatePath, but some docs didn't get updated.
> remove references to nonexistent key_package field in Commit message

- draft-ietf-mls-protocol.md
The unsigned PublicGroupState created by #406 leads to an attack on the new joiner.  The sender of a GroupPublicState can associate any HPKE it wants with the group, and thus learn the `init_secret` without being a member of the group.  (The UpdatePath and the resulting `commit_secret` partly defend against this attack, though they are subverted if the attacker has compromised any single key used in the Update Path.)
To guard against this attack, this PR adds a signature over the HPKE public key in the PublicGroupState.
> Sign the PublicGroupState

- draft-ietf-mls-protocol.md
In preparation for feature-freeze / post-first-WGLC living, this PR removes a few issues that have been discussed and pretty much resolved.  It leaves a few OPEN ISSUES that could benefit from analysis during the feature freeze.
> Remove some stale OPEN ISSUEs

- draft-ietf-mls-protocol.md
This is a small suggestion to move the definition of the `joiner_secret` to the
end of the first Extract-Expand (KDF) cycle of the [key schedule]. This makes
more sense from a cryptographic perspective as we would not be using anything
from the middle of a KDF cycle.
A related suggestion is to remove the `member_secret` from the document. I
removed it from the key schedule, removed all the mentions to forget it as soon
as possible and updated the description of deriving the `welcome_key` and
`welcome_nonce` from the [welcoming new members] section.
[key schedule]: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#key-schedule
[welcoming new members]: https://github.com/mlswg/mls-protocol/blob/master/draft-ietf-mls-protocol.md#welcoming-new-members
> Move joiner_secret to the end of the first KDF cycle in the Key Schedule

- draft-ietf-mls-protocol.md
We had longstanding issue #160 to allow the participants in an MLS group to detect when the DS drops messages.  That issue was closed because it had been open for a long time without a concrete proposed solution.  More recently, however, @raphaelrobert and @beurdouche suggested using a Proposal for this, and it made a lot of sense to me when I looked into the details.  So this PR should be considere joint work between, @raphaelrobert, @beurdouche, and me.
This PR adds an `AppAck` Proposal that any member of the group can send to advertise the last generation it sent, and acknowledge the receipt of application messages from other members.  As a Proposal, it is included in the transcript via Commits, providing a pretty strong defence against message suppression -- the DS basically has to …
> Add an "AppAck" proposal

- draft-ietf-mls-protocol.md
- use `AEAD.Nh` and `AEAD.Nk` instead of `nonce_length` and `key_length`, for consistency with the rest of the spec
- the key and nonce are now derived from the `joiner_secret` rather than randomly chosen
> Editorial changes

- draft-ietf-mls-protocol.md
This pull request makes editorial changes to the definition of Tree Hash  to hopefully make it easier to understand.
It also redefines Parent Hash to include the HPKE public keys to which a nodes secret key was sent. This binds a key package introduced to the ratchet tree in a commit not just to the HPKE keys on the commits direct path but also (indirectly) to the other members that were sent each of the new (secret) keys. 
In particular, this prevents the attacks from the mailinglist that allowed an attacker to create artificial ratchet trees where the tree invariant was violated (which in turn lead to removes failing). But parent_hash only includes the HPKE pubkeys in the resolution so at least some amount of deniability might be preserved.
> Strong tree signing

- draft-ietf-mls-protocol.md
While reviewing #436, I noticed that in one place, we define the initial `interim_transcript_hash` to be the all-zero vector, and in another, we define it to be the empty octet string.  In keeping with the idea of starting chained hashes with the empty octet string, this PR normalizes on the empty octet string for the transcript hashes as well.
> Remove contradictory initialization of transcript hashes

- draft-ietf-mls-protocol.md
Immediately after I published draft-11, @raphaelrobert noticed that I had failed to update the change log.  This PR adds it to the editor's copy, so that it will be included in future versions.
> Add changelog for draft-11

- draft-ietf-mls-protocol.md
Add a missing word. Fail on *blank* leaf.
> Fix typo in Parent Hash verification.

- draft-ietf-mls-protocol.md
Currently the `psks` field in `GroupSecrets` is optional. `PreSharedKeys` only contains an array, which can be empty, even if the option is not empty. To avoid undefined behavior, I removed the option. In case no PSKs are used, the array should simply be empty.
> Make PreSharedKeys non optional in GroupSecrets

- draft-ietf-mls-protocol.md
This PR fixes a few small issues I noticed while reviewing mlspp for compliance with the spec:
* The size of the `Extension.extension_data` vector needs to expand `2^32-1` to support trees for large groups
* The content of the `parent_hash` extension is specified
* `authenticated_data` is included in `MLSPlaintextCommitContent` so that it goes into the transcript
* `MLSPlaintextAuthData` now carries an `optional<MAC>` even though the value is always present, so that the transcript matches the data on the wire
> Minor fixes to message formats

- draft-ietf-mls-protocol.md
draft-08 is the latest HPKE draft, which should be stable. It is also what's being used for interop testing right now.
> Use HPKE draft-08

- draft-ietf-mls-protocol.md
I noticed a bunch of typos in the "IANA Considerations" section: the "ciphersuites" and "credentials" were probably copy-pasted from the "extension" one, and some parts were not changed correctly.
This PR fixes these typos.
> Fix typos in the "IANA Considerations" section

- draft-ietf-mls-protocol.md
The  `select` based on `MLSPlaintextTBS.sender.sender_type` seems ambiguous, as it does not state what happens to cases other than `member`. The TLS presentation language does not say anything on the matter.
> Explicit blank cases in MLSPlaintextTBS

- draft-ietf-mls-protocol.md
This is a proposal to change how the `joiner_secret` is derived. Before, it was derived simply by derivation with a label. This Pull Request updates this step to include the GroupContext, similar to how the `epoch_secret` is derived. Including the GroupContext will give stronger uniqueness guarantees on the `joiner_secret` cryptographically speaking. I think the GroupContext in the derivation of the `epoch_secret` should be kept as it proves that joiners have learned the GroupContext through the Welcome message as well.
> Use the GroupContext to derive the joiner_secret

- draft-ietf-mls-protocol.md
The spec doesn't say anything about the signature encoding yet.
This PR adds a paragraph clarifying that signature encoding is done like in TLS.
> Clarify signature encoding

- draft-ietf-mls-protocol.md
- add the missing `authenticated_data` field to `MLSPlaintextCommitContent`
- the sections for the `Commit` sender and `Commit` receiver seem to have gotten out of sync.  I tried to sync them up (but let me know if I messed something up)
- fix a typo
> more editorial changes

- draft-ietf-mls-protocol.md
After a discussion with @bifurcation and @raphaelrobert, this PR is a new spin on and an extension of #439.
This PR adds the `endpoint_id` field to KeyPackages. The `endpoint_id` field serves to distinguish KeyPackages with Credentials that share the value of their `identity` field.
This PR also introduces a set of restrictions for KeyPackages that introduced to the group via Adds and Updates.
Generally, for both Adds and Updates, the committer has to ensure that
- signature keys are unique within a group (this is so that the sender of a message can be determined uniquely within a group),
- `(identity, endpoint_id)` tuples are unique in a group,
- `hpke_init_key`s are unique in a group.
Additionally, Updates have to ensure that
- the new and the old key package have the same `identity` …
> Revisit the notion of identity in MLS groups

- draft-ietf-mls-protocol.md
@kkohbrok pointed out to me that there's currently no way for a DS to distinguish between MLSPlaintext and MLSCiphertext messages.  Obviously, an application could provide a flag on the outside of a message, but there are a few relatively minor benefits to including a flag in MLS:
* Signing the flag authenticates the sender's intent
* Including the flag in the transcript confirms that all group members got it in the same format
* Including the flag in the struct provides a clear signal as to whether the `membership_tag` needs to be present/verified
Since these benefits are pretty minor, I could kind of go either way on whether to make this change.  But it seemed worth writing up a PR to see what the change would look like.
> Signal the intended wire format for MLS messages

- draft-ietf-mls-protocol.md
@psyoptix pointed out to me some improvements that could be made in the extensibility of proposals.  This PR makes a few changes to smooth out deployment of new proposals:
* Extends `ProposalType` to two bytes, creates an IANA registry, and reserves some space for private use
* Extends the `capabilities` extension so that clients can indicate which proposal types they support
* Forbids committers from including proposals that some people don't support
> Improve extensibility of Proposals

- draft-ietf-mls-protocol.md
In #483, @kkohbrok noted that the concatenation approach used to combine multiple PSKs is not well validated.  At the 2021-10-04 interim, we discussed moving from this approach to a "cascaded HKDF" approach, with the idea of doing the same thing here as the main key schedule.  This PR implements that suggestion.
One nice implication of the algorithm here is that when there are no PSKs, it produces the zero vector as a degenerate case.  So you could implement it pretty cleanly:
```
psk_secret = 0
for psk in psks:
psk_secret = kdf.extract(psk_secret, extract_expand_psk(psk))
```
> Use cascaded KDF instead of concatenation to consolidate PSKs

- draft-ietf-mls-protocol.md
After discussion at the interim 2021-10-04, there seemed to be agreement to move from having two sets of indices (leaf and node indices) to just using node indices.  The main impact of this is that wherever there is a node index in the protocol that is only ever supposed to refer to a leaf node (`Remove.removed`, `GroupInfo.signer_index`, `MLSPlaintext.sender.sender`, `PublicGroupState.signer_index`), the recipient of the message needs to verify that the node index is actually a leaf.  However, implementations already needed to check that these fields were populated leaves, so the change should be minor.
Implementations that were using typed message structures to separate node and leaf indices can continue to use those types to assure that validation is done.  They'll just have to …
> Remove the notion of a 'leaf index'

- draft-ietf-mls-protocol.md
HPKE is in the RFC Editor queue, so there shouldn't be any further changes.
Fixes #500
> Remove explicit version pin on HPKE

- draft-ietf-mls-protocol.md
> Use smaller, fixed-size hash-based identifiers

- draft-ietf-mls-protocol.md
This PR builds on #507 and #521.  It adds the following:
* An explicit note in `Ratchet Tree Terminology` that implementations may use any representation
* A general description of how nodes are added to / removed from the tree
* Specific algorithms for "array-based trees" and "link-based trees"
(I also made a few minor editorial revisions.)
@TWal @franziskuskiefer - I think this hits the right balance of specificity and generality.  Interested in your thoughts here.
> Generalize tree extend/truncate algorithms

- draft-ietf-mls-protocol.md
This PR fixes a typo in `EncryptedGroupSecrets` introduced by PR #491 .
> Fix typo in EncryptedGroupSecrets

- draft-ietf-mls-protocol.md
The padding section was out of date based on prior changes. Resolves #534
> Reword padding section to reflect updated padding structure

- draft-ietf-mls-protocol.md
This PR refactors the two sections on Group Joining (via Welcome and via External Init) by changing the `GroupInfo` struct that can be used for both cases. The `external_pub` used in the course of an External Init is added as an optional field. This PR also:
- removes the redundant ProtocolVersion in the GroupInfo
- adds a GroupInfoTBS struct to follow the convention of specifying a TBS struct for signed messages
- implicitly, the `confirmed_transcript_hash` and `confirmation_tag` is now used for external inits instead of the `interim_transcript_hash`, which was not sufficient to create a valid commit
> Refactor Group Joining and fix External Inits

- draft-ietf-mls-protocol.md
Signatures as specified in the MLS protocol document are ambiguous, in the sense that signatures produced for one purpose in the protocol can be (maliciously) used in a different place of the protocol.
Indeed, we found that for example, a `KeyPackage` can have the same serialization as `MLSPlaintextTBS`, which proves that one signature could be accepted for different structures.
The collisions we have found so far are quite artificial, so it is not super clear how to exploit this, but at least it makes it impossible to have provable security.
The solution is pretty simple, we simply prefix each signed value with a label, in a fashion similar to `ExpandWithLabel`.
That way, when calling `SignWithLabel` you can give the structure name in the `Label` argument.
> Unambiguous signatures

- draft-ietf-mls-protocol.md
#532 proposes to remove redundancy between version fields and ciphersuites by removing the version fields.  This PR removes the version from the ciphersuite instead.
> Remove version from ciphersuites

- draft-ietf-mls-protocol.md
This PR reflects further discussion on #502 and replaces #518.  The high-level impacts are:
* Add clearer, more prescriptive definitions of the re-init and branch operations
* Use a single syntax for all resumption PSKs, but also have a `usage` parameter to distinguish cases
* Allow an `application` usage to cover any other cases defined by applications
Once #520 lands, we should also add some text to the protocol overview to describe these operations.  Pasting some text here for usage in that future PR...
```
A group comprises a single linear sequence of epochs. However, it can sometimes
be useful to express relationships between epochs, either within a group or
across groups.  MLS derives a resumption pre-shared key (PSK) from each epoch to
allow a entropy extracted from one epoch to be …
```
> Tighten up branch and reinit; define ResumptionPSKUsage

- draft-ietf-mls-protocol.md
It doesn't seem super critical, but I think right now there could be a collision between references to Update/Add proposals and KeyPackages. Also, it's essentially free and it just feels wrong not to have proper domain separation for these values 😬.
> Domain separation for KeyPackage and Proposal references

- draft-ietf-mls-protocol.md
Adjust ASCII art to fit within 72 character limit. Did not fix tables or code in appendices.
> Adjust ASCII art to fit within 72 character limit.

- draft-ietf-mls-protocol.md
Addresses the comments in ( Resolves #542 )
Since a member performing a commit including all valid proposals within an epoch is best effort, it makes sense to downgrade the requirement from MUST to SHOULD. 
IMO, MUST should be reserved for instances where the receiver would throw an error in the condition the sender did not 100% comply with the rule. Since in this case it is not a hard error under certain conditions, such as the member performing the commit having not received a proposal in transit while generating the commit, SHOULD is a better choice.
> Downgrade MUST to SHOULD for commit senders including all valid commits

- draft-ietf-mls-protocol.md
The definition of an MLS group in the 2nd paragraph of the Protocol Overview is really good. Let's use it as the definition in the Terminology section as well.
> Make definition of _group_ match the Introduction definition

- draft-ietf-mls-protocol.md
In the most basic case, the resolution of a node is the node, so let's say that.
> Add clarifying note about _resolution_ in the most common case.

- draft-ietf-mls-protocol.md
Make the definition of _descendant_ match the common-sense definition (you are not your own descendant), adjust the text which uses the definition. Note: this allows for a much clearer definition of the tree invariant as well.
> Use common-sense definition of _descendant_

- draft-ietf-mls-protocol.md
The specification currently assumes that a Credential provides a singular identity for a client, when in reality that is not the case.  For example, X509Credential can provide a whole collection of identities, and it's up to the application to decide if its preferred identity is among them.  Just like in TLS, a server can send a cert with 100 domains, but the TLS client knows which one it's looking for.
This PR refactors the parts of the spec that refer to identity to be consistent with this idea.  The main impacts are to processing of Update and Remove-within-External-Commit, both cases in which you want the new KeyPackage to logically represent the same identity as the old one.
This PR also removes the `endpoint_id` field from KeyPackage.  Since we now reference KeyPackages by …
> Be explicit that Credentials can attest to multiple identities

- draft-ietf-mls-protocol.md
As suggested by @rohan-wire to improve the legibility of the document structure.
> Add some subsection divisions to the Commit section

- draft-ietf-mls-protocol.md
This is the last of the reorg PRs.  Does what it says in the title.
> Split the Group State section into Group Context and Transcript Hashes

- draft-ietf-mls-protocol.md
Fix ciphersuite table so the .txt version can fit in 73 chars.
Use the correct separator (-) between table header and the table body for some tables. Some where using the footer separator (=).
> Fix tables in IANA section

- draft-ietf-mls-protocol.md
The definition of blank node needs to move ahead into ## Ratchet Tree Terminology as it is used in the section immediately following (## Views of a Ratchet Tree).
> Move definition of blank node earlier into ## Ratchet Tree Terminology

- draft-ietf-mls-protocol.md
This is a minimal section for MIME type registration of message/mls. 
It assumes that PR #523 include wire_format in all MLS messages (making a format parameter unnecessary),
and that all messages have the MLS version number encoded (making a version parameter unnecessary).
These parameters can be added if needed.
> Add message/mls MIME type registration

- draft-ietf-mls-protocol.md
This PR moves the remark that there has to be validation of the attested identities upon a credential update to the KeyPackage validation subsection. It also changes the responsibility for the check to be that of the AS rather than that of the application. Note, that the boundaries are somewhat arbitrary at this point, since the application running on the local device may well implement parts of the AS. The reason for this change is to ensure any validation checks that pertain to authentication are part of the AS.
> Move validation of identity change to the AS

- draft-ietf-mls-protocol.md
Depends on  #573 
Fixes #539 
This PR implements the suggestion from @TWal in #539, taking into account the discussion on the issue and on the call last week.  There are a bunch of small changes (e.g., changing a lot of `KeyPackageRef` to `LeafNodeRef`), but the critical change is the following split of KeyPackage into LeafNode and KeyPackage:
```
struct {
opaque group_id<0..255>;
opaque parent_hash<0..255>;
} MembershipInfo;
struct {
HPKEPublicKey public_key;
Credential credential;
Capabilities capabilities;
optional<MembershipInfo> membership;
Extension extensions<8..2^32-1>;
// SignWithLabel(., "LeafNodeTBS", LeafNodeTBS)
opaque signature<0..2^16-1>;
} LeafNode;
struct {
ProtocolVersion version;
CipherSuite cipher_suite;
HPKEPublicKey init_key;
Lifetime lifetime;
LeafNode leaf_node; …
```
> Split LeafNode from KeyPackage

- draft-ietf-mls-protocol.md
Fixes #596 
This PR introduces a notion of a proposal type being "path safe", in the sense that it is safe for the path to be omitted.  (Better phrasing welcome!)  The `path` field is required default, and allowed to be omitted only if all the proposals in the Commit are path-safe.
> Require Commit.path by default

- draft-ietf-mls-protocol.md
Changes (apart from editorial):
* Remove the text about the key schedule. Reason: I found the text confusing, because updating paths provides FS and PCS for the HPKE keys in the ratchet tree, and not directly for the key schedule.
* Generate the leaf key pair simply as a fresh HPKE key pair, and not from the leaf_secret. I couldn't see any benefit of using the leaf_secret. I wonder if there is a good reason?
> Clean up the description of tree evolution.

- draft-ietf-mls-protocol.md
The recently introduced variable size encoding allows for very large message sizes that are not practical in any realistic scenario. Since decoders will most likely not allow such large messages anyway, this PR limits the maximum size to 30-bit.
> Limit the new variable length encoding to 30-bit

- draft-ietf-mls-protocol.md
Our proposal
============
The parent hash construction currently authenticates only the public keys in the ratchet tree and does not protect other tree contents, notably the credentials at the leaves.
Consequently, a malicious member can tamper with the credentials before sending a Welcome package to a new member, even if it cannot tamper with the public keys.
Instead of using the tree resolution in the parent hash computation, we propose to use the tree hash.
The last time this was discussed on the list, it was agreed that it would be better to use tree hashes from a security point of view, but it was felt that complexity-wise that the recipient of a Welcome message would have to do O(n^2) work.
A more thorough analysis shows that processing a Welcome message can be done in …
> Stronger parent hashes for authenticated identities

- draft-ietf-mls-protocol.md
PublicGroupState was removed as an independent struct in #529.  This PR fixes some dangling references to it.
> Remove dangling references to PublicGroupState

- draft-ietf-mls-protocol.md
This PR revises the parent hash verification section to reflect more recent discussion.  Right now, the definition of validity according to the parent hash ties it to the "top-down" validation algorithm, when what really matters is that each parent node has a path to a leaf.  This PR changes the definition to that more general version, and mentions the "top-down" and "bottom-up" approaches to checking this property.
> Update parent hash validation

- draft-ietf-mls-protocol.md
This PR:
- consolidates instructions on which key should be used to compute (and verify) a signature on an MLS message depending on the sender type
- reverts #437 
- introduces a `preconfigured_senders` extension that ensures that group members agree on preconfigured signature keys, as discussed in #616 and on the mailing list
Fixes #616.
> Preconfigured senders extension and removal of signature key indirection

- Makefile
- extract-tls.py
Added a short python program to extract the TLS presentation language stanzas into a single file.
Added extract-tls make target to run it.
An equivalent one liner option (only in the Makefile) is commented out.
> Add make target to extract TLS stanzas

- draft-ietf-mls-protocol.md
Continuing to convert more figures to SVG.
The remaining `ascii-art` figures are that way for two reasons:
* Trees with blank nodes `_` render poorly with `aasvg`.  Replacements for the `_` character, like `-`, don't do much better.
* The diagram showing the reuse guard application benefits from the byte-by-byte markers
> More aasvg usage

- draft-ietf-mls-protocol.md
Based on #623 , it should be made explicit that sub-group branching requires a fresh key package for each member. I think there is still a conflict of wording here that I would like feedback on because of this line (which is what triggered me thinking there was a bug)
```
Each LeafNode in the new group's tree MUST be a leaf in the old group's tree at the epoch indicated in the PreSharedKey
```
> Sub-group branching requires fresh key packages for each member

- draft-ietf-mls-protocol.md
The current draft implements the original incorrect version of the tree-hash-for-parent-hash mechanism proposed in #527. That version [breaks in some border cases](https://github.com/mlswg/mls-protocol/pull/527#issuecomment-1020387612). This PR implements the corrected "full-extension + tree hash" mechanism proposed by @TWal [here](https://github.com/mlswg/mls-protocol/pull/527#issuecomment-1035122916).
> Fix parent hash

- draft-ietf-mls-protocol.md
This PR adds a way for the members of a group to indicate the credential types they support, and how to negotiate which credential types may be used in a group.
> Specify compatibility behavior around new credentials.

- draft-ietf-mls-protocol.md
This PR moves the signature key from `Credential` to `LeafNode`, to ensure that an MLS client always has a signature public key with which to verify messages, even if it does not support a member's credential type.
This is an alternative approach to #628, and IMO a bit cleaner.  We no longer need the notion of a SignatureScheme, since BasicCredential doesn't stand alone.  And since Credential only appears in LeafNode, common fields can be hoisted up into LeafNode. The Credential struct really only exists as a conceptual boundary, to make the exposition clearer; otherwise you could just shove the `select` into LeafNode.
Note that this does not obviate the need for #631.  This PR only ensures that the signatures can be processed; that PR helps ensure that the signatures are meaningful.
> Ensure that a signature public key is always intelligible

- draft-ietf-mls-protocol.md
This should have been done before publishing draft-14, but we can't fix that now.  At least this will capture the history in draft-15.
> Add draft-14 changelog

- draft-ietf-mls-protocol.md
Fixes #642 
Also requires that padding be all-zero.  Before, the sender was allowed to put arbitrary octets in there.
> Make padding arbitrary-size and all-zero

- draft-ietf-mls-protocol.md
This seems to be a layer of indirection that doesn't add any value to implementation.
> Replace LeafNodeRef with leaf index.

- draft-ietf-mls-protocol.md
Sending an Add proposal from outside the group is how we let people do "external add" functionality without needing to publish the group state. But you can't talk right away like you can with an external Commit. In that case, applications seem more inclined to build this functionality themselves so let's just remove it from the spec.
> Remove new_member Add proposals.

- draft-ietf-mls-protocol.md
Closes #670 
Closes #644 
Closes #669 
This PR reorganizes the exposition of tree concept to make them read more clearly.
* A new Paths through the Ratchet Tree section is introduced, which covers direct paths, copaths, and filtered direct paths
* The Ratchet Tree Nodes section is moved forward, so that the definition of filtered direct paths can refer to the notion of resolutions (see @Bren2010's note on #670)
* The path example expanded so that there are blanks in the tree, and so that it shows all three path types (direct, copath, and filtered direct) for every leaf.
* The section on verifying parent hashes uses the example tree from the path section to illustrate the concepts noted in #669
> Reorganize discussion of ratchet tree concepts

- draft-ietf-mls-protocol.md
> Update external senders extension.

- draft-ietf-mls-protocol.md
Closes #663. I'm not sure if this is actually necessary, but there usually seem to be issues in Merkle trees when the leaves are not explicitly distinct from the parents.
> Add a marker byte to tree hash input structs.

- draft-ietf-mls-protocol.md
At first I was going to make `external_key_id` an extension for both KeyPackages and LeafNodes. But I was thinking and couldn't come up with a reason for KeyPackages to need this extension, so did just LeafNode. Closes #696.
> Change KeyPackage identifier to be LeafNode identifier.

- draft-ietf-mls-protocol.md
> Clarify some parts of Application Messages section.

- draft-ietf-mls-protocol.md
Closes #678 
Replaces #660 
This PR attempts to add precision to the credential validation requirements in the document, along the lines @raphaelrobert suggests in #678, in the spirit of what @Bren2010 wrote up in #660 and drawing inspiration from what RFC 6125 does in the context of TLS.  It seems like this gives a clearer definition of (a) what the AS's job is and (b) when it needs to be done.
> Be more precise about credential validation

- draft-ietf-mls-protocol.md
> Derive the commit secret from the end of the UpdatePath, not the root

- draft-ietf-mls-protocol.md
While reviewing #713, I realized that we have a potential interop problem around `ParentNode.unmerged_leaves`.  This struct feeds into the tree hash, so everyone in the group needs to have the entries in the same order or else they'll disagree on the tree hash.  But the order isn't specified anywhere: All the document says right now is "add L's leaf index to the unmerged_leaves list", which could be implemented as an insert anywhere in the list.  This PR resolves the ambiguity by requiring the list be sorted.
> Require that unmerged_leaves be ordered

- .gitignore
Currently `make extract-tls` generates a file with all the TLS Presentation Language structs. Add this file to `.gitignore`
> Make git ignore the output of make extract-tls

- draft-ietf-mls-protocol.md
Closes #673 
Closes #674 
With regard to #674: I searched for references to MLSPlaintext and Credential that were obsolete in light of the change to the MLSMessage framework.  (In particular, we used to have the idea that you would encode things as MLSPlaintext, then tranform them to MLSCiphertext if needed; now you encode to AuthenticatedContent and then convert that to MLSPlaintext/MLSCiphertext before sending.)  There were a few fixes for MLSPlaintext; I didn't find anything that needed fixing for Credentia, largely thanks to some PRs that have landed since I did the review that resulted in #674.
> Clean up struct names and references to them

- draft-ietf-mls-protocol.md
Closes #655 
Depends on #694 
Conflicts with #713 
The diff here is messy because it includes #694.  The biggest change is the extended example, for which you can just scroll to the bottom.
> Clarify tree hash and parent hash

- draft-ietf-mls-protocol.md
Fixes #671 
Conflicts with #707 (in derivation of `commit_secret`)
This is intended just to move around the required steps and give them clearer labels.  Please keep an eye out for things that might have accidentally been added or dropped.
> Clarify description of UpdatePath generation and processing

- draft-ietf-mls-protocol.md
The goal of #527 was to have a property similar to:
> If there is a parent-hash chain from the leaf L to a node N, then the signature of L binds the tree Canonicalize(N)
(where Canonicalize(N) is N with its unmerged leaves removed, i.e. the subtree of N the last time a Commit went through it)
However, this is currently not true, there are a few places where we can do (hopefully benign) modifications on N.
Example 1:
```
W
______|_____
/             \
_               Y
__|__           __|__
/     \         /     \
T       _       X       Z
/ \     / \     / \     / \
A   B   _   _   E   F   G   H
```
with the parent-hash chain A-T-W (happening with filtered update path).
We can modify the blank subtree:
```
W
______|_____
/             \
_               Y
__|__           __|__
/     \ …
```
> Improve parent hash guarantees

- draft-ietf-mls-protocol.md
This will guarantee that all group members agree on the ciphersuite used. It gives more meaning to statements like "Each MLS session uses a single ciphersuite".
Also, it prevents the following attack: the adversary (a malicious insider) invites someone and convinces them that the group uses a ciphersuite with say a signature scheme that is weaker but still compatible with the one actually used. Now the new member uses a weaker scheme and the adversary can impersonate them.
> Include ciphersuite in group context

- draft-ietf-mls-protocol.md
`external_senders` was missing from the Extension Types table so it didn't have an extension type value assigned
> Add `external_senders` to MLS Extension Types registry

- draft-ietf-mls-protocol.md
The `confirmation_tag` was missing. The error was introduced in #706.
This kind of error makes me wonder if the redundancy between the `...` and the `...TBS` really are necessary.
In my code, I use a pattern like this:
```
struct {
GroupContext group_context;
Extension extensions<V>;
MAC confirmation_tag;
uint32 signer;
} GroupInfoTBS;
struct {
GroupInfoTBS tbs;
// SignWithLabel(., "GroupInfoTBS", GroupInfoTBS)
opaque signature<V>;
} GroupInfo;
```
No copy-paste error possible! Looks a bit weird, but if we replace "tbs" by "data", it makes more sense.
> Fix GroupInfoTBS

- draft-ietf-mls-protocol.md
As @fluffy pointed out on the mailing list, this reference does not need to be normative.
> Make reference to h2 informative

- draft-ietf-mls-protocol.md
Early review from IANA indicated that we had not completed the [full template](https://datatracker.ietf.org/doc/html/rfc6838#section-5.6).  This PR adds the missing fields.
> Complete IANA media type registration

- draft-ietf-mls-protocol.md
The goal of #527 and #713 was to have a property similar to:
> If there is a parent-hash chain from the leaf L to a node N, then the signature of L binds the tree Canonicalize(N)
In #713, I proved that the pull-request allowed to prove the following property:
> If Canonicalize(U1) = Canonicalize(U2),
> and there is a parent-hash link from U1 to P1 and from U2 to P2,
> then Canonicalize(P1) = Canonicalize(P2)
With this property, the hope is to inductively show that the leaf signature binds the canonicalization of subtrees it is parent-hash linked from.
The induction step works fine thanks to the previous theorem, however the base case is wrong.
The hypothesis "Canonicalize(U1) = Canonicalize(U2)" says that the content of the trees are equal, and also says they have the same location (i.e. …
> Include leaf index in LeafNodeTBS for better parent-hash guarantees

- draft-ietf-mls-protocol.md
The part about doing the lookup in the old tree was added in #491, it was relevant here because of the hash references.
This is not a problem anymore since we came back to referencing with leaf index.
> Simplify Remove section

- draft-ietf-mls-protocol.md
For consistency with references to other extensions (and with the IANA registry), refer to the extension as "external_pub".
> Change to external_pub

- draft-ietf-mls-protocol.md
- The `ResumptionPSKUsage` enum was missing the `u8` limit.
- The `GroupContextExtensions` wasn't using a TLS environment.
> Add limit to ResumptionPSKUsage

- draft-ietf-mls-protocol.md
Fixes #738 
... by just importing the [current text in 8447bis](https://www.ietf.org/archive/id/draft-ietf-tls-rfc8447bis-01.html#name-adding-recommended-column).  @seanturner lmk if you think we should reference instead.
> Update Recommended column definition to match 8447bis

- draft-ietf-mls-protocol.md
> Use C-style comments in TLS presentation syntax

- draft-ietf-mls-protocol.md
https://mailarchive.ietf.org/arch/msg/mls/o-2RdSTL2VV-k0NQ_52Fg6A8zqo/
> Responses to early OPSDIR review

- draft-ietf-mls-protocol.md
Fixes #753 
This initial effort tweaks the sections that talk about generating and processing Welcome messages.  There might be other references to a single Welcome per Commit that should be amended for clarity.  Someone should audit for those before we merge this PR.
> Allow multiple welcomes per commit

- draft-ietf-mls-protocol.md
Update all tables to use hyphens for table dividers instead of equal signs. Suggesting this because using equal signs leads to the tables not being rendered correctly on GitHub (preview below).
I tried to see if there's a reason for using one over the other, but couldn't find one. If there's some reason to use equal signs, or if this is considered a non-issue, feel free to close this.
---
| this  | is    | an    | example |
|:======|:======|:======|:========|
| using | equal | signs | `=`     |
| this  | is      | an      | example |
|:------|:--------|:--------|:--------|
| using | hyphens | instead | `-`     |
> Update table header dividers

- draft-ietf-mls-protocol.md
This PR fixes some minor issues with the presentation language. Moving `SignContent` and `RefHashInput` to their own `~~~ tls` block is required so that the `extract-tls.py` can now detect them.
> editorial: Minor fixes in presentation language.

- draft-ietf-mls-protocol.md
Fixes #762
Fixes #763
Fixes #815
Fixes #813
* Add a paragraph to Operational Context describing additional security services that the DS can provide
* Add a citation to security analyses via the MLS Architecture
* Add a section discussing metadata protection
> Update security and operational considerations

- draft-ietf-mls-protocol.md
Fixes #840 
Also copies the "Recommended" field by reference, instead of reciting it in each registry.
Note that this has a conflict with #839 that `git` will not catch -- "MLSContentTBS" will have to be changed to whatever new name is agreed in that PR.
> Create IANA registries for signature and export labels

- draft-ietf-mls-protocol.md
In discussion of #834, it came up that the current tree validation rules are loose enough that they allow configurations of `unmerged_leaves` that could not come about by normal operations.  This PR adds a check to enforce that if a node is unmerged at a parent node, it is also unmerged at every node between that parent node and the unmerged leaf.  
This is clearly a necessary property of any honestly-created tree, given the way `unmerged_leaves` entries are set and cleared (including the possible changes in #834).  I think it is also sufficient, but I don't have a proof on hand.
> Validate additional properties of unmerged leaves

- draft-ietf-mls-protocol.md
Fixes #759 
As discussed in #759, this PR makes the following terminology changes:
| Before                      | After                     |
|:----------------------------|:--------------------------|
| MLSMessage                  | MLSMessage                |
| MLSContent                  | GroupContent              |
| MLSContentTBS               | GroupContentTBS           |
| MLSContentAuthData          | GroupContentAuthData      |
| MLSAuthenticatedContent     | AuthenticatedContent      |
| MLSContentTBM               | AuthenticatedContentTBM   |
| MLSSenderData               | SenderData                |
| MLSSenderDataAAD            | SenderDataAAD             |
| MLSCiphertextContent        | AuthenticatedContentTBE   |
| MLSCiphertextContentAAD     | ContentAAD …
> Remove "MLS" prefix on structs

- draft-ietf-mls-protocol.md
As discussed in the virtual interim 2022-12-16, it is possible that extensions might be tempted to re-use HPKE public keys created for MLS.  Even within MLS, we have two different public-key encryption cases, Welcome and Commit (though these currently use different keys).
Currently, for Commit encryption, the HPKE `info` parameter is set to the group context.  The content of `info` is actually undefined for Welcome encryption (!)  This PR makes the following changes:
* Define general `EncryptWithLabel` and `DecryptWithLabel` functions that populte the HPKE `info` parameter with an encoded label and context
* Apply these to Commit and Welcome encryption:
* Commit: label="UpdatePathNode", context=`group_context`
* Welcome: label="Welcome", context=`encrypted_group_info`
* Add an IANA …
> Add label and context to public-key encryption

- draft-ietf-mls-protocol.md
Just stumbled over these remaining occurrences of plaintext/ciphertext. Was this intentional?
> cleanup after plaintext and ciphertext renaming.

- draft-ietf-mls-protocol.md
Yes, this is not minimal (@sureshkrishnan suggested something closer to that), but I think that this is easier again to understand.
A smaller version checks against `1 << (4*len - 2)`, but that doesn't make much sense.
> A different check for the length code

- draft-ietf-mls-protocol.md
https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/ballot/#draft-ietf-mls-protocol_lars-eggert
> IESG Review by Lars Eggert

- draft-ietf-mls-protocol.md
https://datatracker.ietf.org/doc/draft-ietf-mls-protocol/ballot/#draft-ietf-mls-protocol_erik-kline
> IESG Review by Erik Kline

- draft-ietf-mls-protocol.md
The current text on initializing the transcript hash is ambiguous.  In particular, it never tells you how to compute the first `interim_transcript_hash`. This PR provides clearer initialization instructions, and a figure that summarizes the transcript hash evolution [2].
[1] To be clear, I think the intent is clear and all current implementations are consistent.  The text is just bad.
[2] The diagram is a little over-the-top elaborate.  I would be OK removing it :)
> Clarify transcript hash initialization

- draft-ietf-mls-protocol.md
Currently the "exporter" label is used two times : to derive `exporter_secret`, and in `MLS-Exporter`.
I'm not sure it's really problematic, but using different labels doesn't cost much, hence this PR.
> Change MLS-Exporter label from "exporter" to "exported"

- draft-ietf-mls-protocol.md
Fix a bug noticed by @bifurcation. Using `ExpandWithLabel` instead of the raw `Expand` seems the right way. Note that after this change "MLS 1.0" is prepended to the label.
> Use ExpandWithLabel to derive welcome key

- draft-ietf-mls-protocol.md
As discussed in mlswg/mls-implementations#102 .
Currently, there are several valid `ratchet_tree` for one tree: the sender can choose ("SHOULD") to omit some (but not all) blank nodes at the right of the tree.
This PR changes this: the sender MUST omit all the blank nodes at the right of the tree, and the receiver MUST check that it was done correctly (i.e., the last node of `ratchet_tree` is non-blank).
> Make the ratchet tree non-malleable

- draft-ietf-mls-protocol.md
As discussed in #867, remove the `TBE` for more consistency across names.
> Rename `PrivateContentTBE` to `PrivateMessageContent`

- draft-ietf-mls-protocol.md
This PR fixes small issues that I noticed while implementing proposal validation and fixing some external join bugs:
* The pseudocode for determining whether a path is required assumes that all proposals are by-reference.  The PR updates the pseudocode to be more general, and also account for proposals by value.
* There were two references to adding a single leaf to the tree, which are updated to make clear that the tree grows by doubling, not by single leaves.
* There was no current requirement that an Update proposal have a distinct `encryption_key`, so one is added.
> Three small edits

- draft-ietf-mls-protocol.md
This updates the language around how certificate chains are constructed:
- We allow certificates to be omitted if the client knows any recipients will already possess the omitted certificate.
- We allow certificate chains to be out-of-order and potentially contain unused certificates.
This is nice because it means less data needs to be sent on the wire, and also provides a method for root certificates to be rotated gracefully (as clients can provide chains for both old and new roots).
> #860: Loosen chain requirements.

- draft-ietf-mls-protocol.md
This removes the following graf:
The DS and AS may also apply additional policies to MLS operations to obtain
additional security properties.  For example, MLS enables any participant to add
or remove members of a group; a DS could enforce a policy that only certain
members are allowed to perform these operations.  MLS authenticates all members
of a group; a DS could help ensure that only clients with certain types of
credential are admitted. MLS provides no inherent protection against denial of
service; A DS could also enforce rate limits in order to mitigate
these risks.
My sense is this belongs in Security Considerations, not here.
> Add some more explanatory text to the beginning.

- draft-ietf-mls-protocol.md
This PR is an attempt to address #856.  It registers GREASE code points in the relevant registries and recommends their use in the appropriate places.  It also includes some edits to the extensibility provisions to make them clearer and sharper, and a little cleanup on registry formatting.
Fixes #856
> GREASE for MLS registries

- draft-ietf-mls-protocol.md
Nick sent me some late comments, which I have reflected in this PR.  The most significant changes are:
* A new section in the overview covering external commits, so that that concept has been introduced before it is encountered further down.
* A new subsection in the security considerations elaborating why key uniqueness mattes, and some slightly stronger requirements around it in the appropriate spots.
> Comments from Nick Sullivan

- draft-ietf-mls-protocol.md
@mulmarta and I have completed interop testing that covers all of the functionality in the spec.  We found a couple of places where there were ambiguities in the spec that led to different implementation decisions, and in the process of resolving those, found a couple of errors / omissions in drarft-19.
* The current PSK proposal validation forbids `resumption` with `usage` other than `applications`.  The branch and reinit sections call for the creation of PSK proposals with types `branch` and `reinit`.  Given the text in the PSK section, these proposals would be invalid.  This PR explicitly allows `branch` and `reinit` in the specific context of those operations.  (This is a little pro-forma, since the PSK proposals are only seen by the committer.  But it seems good to allow the …
> Resolve ambiguities found in interop testing
